/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package impiantoElettrico;

import java.awt.Color;
import javax.swing.JToggleButton;

/**
 * Not è l'unica porta logica che non è figlia di "PortaLogica" in quanto non ammette un solo input
 * @author Giuseppe
 */
public class Not extends javax.swing.JPanel {

    JToggleButton input;
    JToggleButton stato;
    
    public Not() {
        initComponents();
        stato= new JToggleButton();
        stato.setVisible(false);
    }
    
    
    public void aggiungiInput(JToggleButton bottone) {
        input = bottone;
    }
    
    public JToggleButton restituisciOutput() {
            
        cambiaStato(!input.isSelected());
        return stato;
    }
    
    private void cambiaStato(boolean output){
        if (output){
            this.setBackground(Color.GREEN);
            stato.setSelected(true);
        } else {
            this.setBackground(Color.RED);
            stato.setSelected(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
