/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package impiantoElettrico;

import java.awt.Color;
import java.util.Set;
import javax.swing.JToggleButton;

/**
 * Classe Genitore di tutte le altre porte logiche (ad eccezione di Not)
 * utilizza dei JtoggleButton per prendere l'input e come output in modo da poterlo passare alle altre porte logiche
 * @author Giuseppe
 */
public abstract class PortaLogica extends javax.swing.JPanel {

    
    Set input;
    JToggleButton input1;
    JToggleButton input2;
    JToggleButton stato;
 
    
    public PortaLogica() {
        initComponents();
        stato = new JToggleButton();
        stato.setVisible(false);
    }
    
    public abstract JToggleButton restituisciOutput();
    
    public void aggiungiPrimoInput(JToggleButton bottone){
        input1 = bottone;
    }
    
    public void aggiungiSecondoInput(JToggleButton bottone){
        input2 = bottone;
    }
    
    public void aggiungiInput(JToggleButton bottone){
        input.add(bottone);
    }
    
    protected void cambiaStato(boolean output){
        if (output){
            this.setBackground(Color.GREEN);
            stato.setSelected(true);
        } else {
            this.setBackground(Color.RED);
            stato.setSelected(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(100, 0, 65));
        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setMinimumSize(new java.awt.Dimension(55, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
