/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rompicapo;


import java.awt.BorderLayout;

import java.awt.event.MouseEvent;
import java.util.function.Consumer;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.MouseInputAdapter;

/**
 * Classe che implementa un minigioco in cui bisogna mettere i libri in un determinato ordine,
 * i libri sono dei pannelli che se cliccati sono presi dal mouse e occupano "pannelloPreso" per
 * evitare di prendere più pannelli contemporaneamente, il tasto infine serve a confermare la scelta
 *
 * @author Giuseppe
 */
public class LibreriaRompicapo extends javax.swing.JPanel {
    
    //pannelloPreso serve per rendere  l'interazione con i bloocchi un operazione "atomica",
    //una volta che un blocco viene preso avrà priorità sul controllo del mouse fino al rilascio
    JPanel pannelloPreso;
    Consumer libreria;
    
    static boolean pannelloRisolto = false;
    /**
     * Creates new form PannelloRompicapo
     * @param libreria implementazione di un interfaccia funzionale Consumer in modo da 
     *          poter ottenere oggetti e dare mesaggi all'utente
     */
    public LibreriaRompicapo(Consumer libreria) {
        initComponents();
        pannelloPreso = null;

        this.libreria = libreria;
        
        caricaImmagini();
        setComponentZOrder(mensola,0);
        setComponentZOrder(sfondo,1);
        SensoreMouse mouse = new SensoreMouse();
        addMouseMotionListener(mouse);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensola = new javax.swing.JPanel();
        libro1 = new javax.swing.JPanel();
        libro2 = new javax.swing.JPanel();
        libro3 = new javax.swing.JPanel();
        libro6 = new javax.swing.JPanel();
        libro4 = new javax.swing.JPanel();
        libro5 = new javax.swing.JPanel();
        bottoneConferma = new javax.swing.JButton();
        sfondo = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(700, 30000));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(754, 354));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new javax.swing.OverlayLayout(this));

        mensola.setMinimumSize(new java.awt.Dimension(580, 231));
        mensola.setOpaque(false);

        libro1.setOpaque(false);
        libro1.setPreferredSize(new java.awt.Dimension(44, 156));

        javax.swing.GroupLayout libro1Layout = new javax.swing.GroupLayout(libro1);
        libro1.setLayout(libro1Layout);
        libro1Layout.setHorizontalGroup(
            libro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        libro1Layout.setVerticalGroup(
            libro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        libro2.setOpaque(false);
        libro2.setPreferredSize(new java.awt.Dimension(44, 156));

        javax.swing.GroupLayout libro2Layout = new javax.swing.GroupLayout(libro2);
        libro2.setLayout(libro2Layout);
        libro2Layout.setHorizontalGroup(
            libro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        libro2Layout.setVerticalGroup(
            libro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        libro3.setOpaque(false);
        libro3.setPreferredSize(new java.awt.Dimension(44, 156));

        javax.swing.GroupLayout libro3Layout = new javax.swing.GroupLayout(libro3);
        libro3.setLayout(libro3Layout);
        libro3Layout.setHorizontalGroup(
            libro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        libro3Layout.setVerticalGroup(
            libro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        libro6.setMaximumSize(new java.awt.Dimension(32767, 130));
        libro6.setOpaque(false);
        libro6.setPreferredSize(new java.awt.Dimension(44, 156));

        javax.swing.GroupLayout libro6Layout = new javax.swing.GroupLayout(libro6);
        libro6.setLayout(libro6Layout);
        libro6Layout.setHorizontalGroup(
            libro6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        libro6Layout.setVerticalGroup(
            libro6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        libro4.setOpaque(false);
        libro4.setPreferredSize(new java.awt.Dimension(44, 156));

        javax.swing.GroupLayout libro4Layout = new javax.swing.GroupLayout(libro4);
        libro4.setLayout(libro4Layout);
        libro4Layout.setHorizontalGroup(
            libro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        libro4Layout.setVerticalGroup(
            libro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        libro5.setOpaque(false);
        libro5.setPreferredSize(new java.awt.Dimension(44, 156));

        javax.swing.GroupLayout libro5Layout = new javax.swing.GroupLayout(libro5);
        libro5.setLayout(libro5Layout);
        libro5Layout.setHorizontalGroup(
            libro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        libro5Layout.setVerticalGroup(
            libro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bottoneConferma.setText("confirm");
        bottoneConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneConfermaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mensolaLayout = new javax.swing.GroupLayout(mensola);
        mensola.setLayout(mensolaLayout);
        mensolaLayout.setHorizontalGroup(
            mensolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensolaLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(libro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(libro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(libro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mensolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mensolaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(bottoneConferma))
                    .addGroup(mensolaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(libro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(libro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(libro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        mensolaLayout.setVerticalGroup(
            mensolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensolaLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(mensolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(libro3, 155, 155, Short.MAX_VALUE)
                    .addComponent(libro2, 155, 155, Short.MAX_VALUE)
                    .addComponent(libro4, 155, 155, Short.MAX_VALUE)
                    .addComponent(libro5, 155, 155, Short.MAX_VALUE)
                    .addComponent(libro6, 155, 155, Short.MAX_VALUE)
                    .addComponent(libro1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(bottoneConferma)
                .addGap(39, 39, 39))
        );

        add(mensola);

        sfondo.setOpaque(false);

        javax.swing.GroupLayout sfondoLayout = new javax.swing.GroupLayout(sfondo);
        sfondo.setLayout(sfondoLayout);
        sfondoLayout.setHorizontalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        sfondoLayout.setVerticalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        add(sfondo);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    //controllo della soluzione del rompicapo e chiama ta della funzione in caso di riuscita
    private void bottoneConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneConfermaActionPerformed
        //inserire condizione per finire rompicapo
        if(libro6.getX() < libro1.getX() && libro1.getX() < libro4.getX() && libro4.getX() < libro2.getX()
                && libro2.getX() < libro5.getX() && libro5.getX() < libro3.getX()){
            
           if(!pannelloRisolto){
               pannelloRisolto = true;
               libreria.accept(true);
           }
        }
    }//GEN-LAST:event_bottoneConfermaActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        //reset dei falg di "proprietà del puntatore" su rilascio del mouse
        if(evt.getButton() == MouseEvent.BUTTON1){
            pannelloPreso = null;
        }
    }//GEN-LAST:event_formMouseReleased


    //classe che implementa un interfaccia mouse iput adapter, per prelevare ò'inpurat dal mouse
    private class SensoreMouse extends MouseInputAdapter{

        @Override
        public void mouseDragged(MouseEvent e) {
            
            if(mouseSuPannello(mensola,e)){
                if(pannelloPrendibile(libro1, e)){
                    prendiSpostaPannello(libro1, e);
                } else if (pannelloPrendibile(libro2, e)){
                    prendiSpostaPannello(libro2, e);
                } else if (pannelloPrendibile(libro3, e)){
                    prendiSpostaPannello(libro3, e);
                } else if (pannelloPrendibile(libro6, e)){
                    prendiSpostaPannello(libro6, e);
                } else if (pannelloPrendibile(libro4, e)){
                    prendiSpostaPannello(libro4, e);
                } else if (pannelloPrendibile(libro5, e)){
                    prendiSpostaPannello(libro5, e);
                }
            }

        }
    }
    
    private void prendiSpostaPannello(JPanel pannello, java.awt.event.MouseEvent evt){
        pannelloPreso = pannello;
        pannello.setLocation(evt.getX() - (pannello.getWidth()/2) ,pannello.getY());
    }
    
    private boolean pannelloPrendibile(JPanel pannello, java.awt.event.MouseEvent evt){
        return mouseSuPannello(pannello, evt) && (pannelloPreso == null || pannelloPreso.equals(pannello));
    }
    
    
    private boolean mouseSuPannello(JPanel pannello, MouseEvent e) {
        boolean flagCursoreSuPannello = false;
        
        int x = e.getX();
        int y = e.getY();
        int pannelloMinX = pannello.getX();
        int pannelloMaxX = pannelloMinX + pannello.getWidth();
        int pannelloMinY = pannello.getY();
        int pannelloMaxY = pannelloMinY + pannello.getHeight();
        if(pannelloMinX < x && x < pannelloMaxX && pannelloMinY < y && y < pannelloMaxY){
            flagCursoreSuPannello = true;
        }
        
        return flagCursoreSuPannello;
    }
        
    private void caricaImmagini(){

            immagineInPannello("./img/libreria/mensolaMigliore.png", sfondo );
            immagineInPannello("./img/libreria/libroSpadoneRompicapo.png", libro1);
            immagineInPannello("./img/libreria/libroLacciRompicapo.png", libro2);
            immagineInPannello("./img/libreria/libroHpRompicapo.png", libro3);
            immagineInPannello("./img/libreria/libroAlberoRompicapo.png", libro6);
            immagineInPannello("./img/libreria/libroUomoTunicaRompicapo.png", libro4);
            immagineInPannello("./img/libreria/libroSabRompicapo.png", libro5);
            
    }   
    
    private void immagineInPannello(String percorsoImmagine, JPanel pannello){
        ImageIcon icona = new ImageIcon(percorsoImmagine);
        JLabel label = new JLabel( icona);
        pannello.setLayout(new BorderLayout());
        pannello.add(label);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneConferma;
    private javax.swing.JPanel libro1;
    private javax.swing.JPanel libro2;
    private javax.swing.JPanel libro3;
    private javax.swing.JPanel libro4;
    private javax.swing.JPanel libro5;
    private javax.swing.JPanel libro6;
    private javax.swing.JPanel mensola;
    private javax.swing.JPanel sfondo;
    // End of variables declaration//GEN-END:variables
}
